version: 2

python:
  install:
    - requirements: docs/requirements.txt
    #- requirements: requirements.txt
    - method: pip
      path: .
  commands:
    - pip install poetry
    - poetry install
  system_packages: true
