version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.7'
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - |
        . "$(pwd | rev | sed 's/stuokcehc/svne/' | rev)/bin/activate"
        && cd sanic_praetorian
        && poetry install --no-interaction --no-root

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true