[tool.poetry]
name = "sanic-praetorian"
version = "2.0.0_rc3"
description = "Strong, Simple, (now async!) and Precise security for Sanic APIs (using jwt)"
authors = ["Rob Dailey <rob@suspected.org>"]
license = "MIT"
readme = "README.rst"
homepage = "https://sanic-praetorian.readthedocs.io/en/latest/"
documentation = "https://sanic-praetorian.readthedocs.io/en/latest/"
repository = "https://github.com/pahrohfit/sanic-praetorian"

[project.urls]
"Homepage" = "https://sanic-praetorian.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/pahrohfit/sanic-praetorian/issues"

[tool.poetry.dependencies]
python = "^3.7"
pyjwt = "^2.0"
pendulum = "^2.1"
passlib = "^1.7"
sanic = "^22.6.0"
sanic-ext = "^22.6.2"
simple-settings = "^1.2.0"
Jinja2 = "^3.1.2"
sanic-mailing = {git = "https://github.com/pahrohfit/sanic-mailing.git", rev = "development"}
segno = "^1.5.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^3.7"
bcrypt = "^3.1"
ipdb = "^0.12.0"
plummet = {version = "^1.1", extras = ["time-machine"]}
sanic-testing = "^22.6.0"
sanic-ext = "^22.6.2"
pytest-asyncio = "^0.18.3"
tortoise-orm = "^0.19.2"
nest-asyncio = "^1.5.5"
pytest-cov = "^3.0.0"
toml = "^0.10.2"
sphinx-rtd-theme = "^1.0.0"
sphinx = "^5"
umongo = "3.1.0"
mongomock = "4.1.1"
mongomock-motor = "^0.0.12"
motor = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.1"]
build-backend = "poetry.core.masonry.api"
