name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  pypi_release:
    name: Build using Poetry and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: login
      run: poetry config http-basic.pypi __token__ ${{ secrets.PYPI_PASSWORD }}
    - name: build
      run: poetry build
    - name: publish
      run: poetry publish
