name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  pypi_release:
    name: Build using Poetry and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: login
      run: poetry config http-basic.pypi __token__ ${{ secrets.PYPI_PASSWORD }}
    - name: build
      run: poetry build
    - name: publish
      run: poetry publish
