name: Publish to Test PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: setup pypi testing env
      run: poetry config repositories.testpypi https://test.pypi.org/
    - name: login
      run: poetry config http-basic.pypi __token__ ${{ secrets.PYPI_TESTING_PASSWORD }}
    - name: build
      run: poetry build
    - name: publish
      run: poetry publish
